version: "3.5"
services:
  backend:
    build:
      context: ./
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      NODE_ENV: "production"
      PORT: 5000
    env_file: .env.dev
