version: "3.5"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env.dev
    ports:
      - "3306:3306"
    expose:
      - "3306"
    security_opt:
    - seccomp:unconfined
    volumes:
      - db-dev:/var/lib/mysql
  backend:
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./src:/home/app/src
      - ./tsconfig.json:/home/app/tsconfig.json

    environment:
        NODE_ENV: "development"

volumes:
  db-dev:
